version: '3.8'

services:
  rotina-cura:
    image: pabloalmeiida/rotina-cura:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.rotina-cura.rule=Host(`seudominio.com.br`)
      - traefik.http.routers.rotina-cura.entrypoints=websecure
      - traefik.http.routers.rotina-cura.tls.certresolver=le
      - traefik.http.routers.rotina-cura.tls=true
      - traefik.http.services.rotina-cura.loadbalancer.server.port=80
    deploy:
      restart_policy:
        condition: any
